version: '3.7'
services:

  api:
    container_name: api
    build:
      context: ./proj
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./proj:/app
    env_file: 
      - ./env/.env
      - ./env/.env.private
    ports:
      - 8080:80
    restart: on-failure
    networks:
      - fabrique-net
    depends_on:
      - db

  celery:
    container_name: celery
    build:
      context: ./proj
      dockerfile: Dockerfile
    command: celery -A proj worker --loglevel=INFO --uid=nobody --gid=nogroup
    volumes:
      - ./proj:/app
    env_file:
      - ./env/.env
      - ./env/.env.private
    networks:
      - fabrique-net
    restart: on-failure
    depends_on:
      - db
      - api
      - redis

  celery-beat:
    container_name: celery-beat
    build:
      context: ./proj
      dockerfile: Dockerfile
    command: celery -A proj beat --loglevel=INFO --uid=nobody --gid=nogroup
    volumes:
      - ./proj:/app
    env_file:
      - ./env/.env
      - ./env/.env.private
    networks:
      - fabrique-net
    restart: on-failure
    depends_on:
      - db
      - api
      - redis

  db:
    container_name: db
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file: ./env/.env
    ports:
      - 5432:5432
    restart: always
    networks:
      - fabrique-net

  redis:
    image: redis
    container_name: redis
    ports:
      - 6381:6379
    networks:
      - fabrique-net
    restart: on-failure

  flower:
    container_name: flower
    image: mher/flower
    env_file: ./env/.env
    networks:
      - fabrique-net
    restart: on-failure
    ports:
      - 5556:5555
    depends_on:
      - redis

networks:
  fabrique-net:
    external: true
    driver: bridge